name: Lint

on:
  - pull_request

jobs:
  Lint:
    runs-on: ubuntu-latest

    - steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Lint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: *.md
          ignore_files: README.md
